# -*- coding: UTF-8 -*-

SCENE_PRESET0 = 0
SCENE_PRESET1 = 5
SCENE_PRESET2 = 17
SCENE_PRESET3 = 18
SCENE_PRESET4 = 19
SCENE_PRESET5 = 20
SCENE_AUTO_STANDBY = 64
SCENE_PANIC = 65
SCENE_ENERGY_OVERLOAD = 66
SCENE_STANDBY = 67
SCENE_DEEP_OFF = 68
SCENE_SLEEPING = 69
SCENE_WAKEUP = 70
SCENE_PRESENT = 71
SCENE_ABSENT = 72
SCENE_DOOR_BELL = 73
SCENE_ALARM_1 = 74
SCENE_ROOM_WAKEUP = 75
SCENE_FIRE = 76
SCENE_ALARM_2 = 83
SCENE_ALARM_3 = 84
SCENE_ALARM_4 = 85
SCENE_WIND = 86
SCENE_NO_WIND = 87
SCENE_RAIN = 88
SCENE_NO_RAIN = 89
SCENE_HAIL = 90
SCENE_NO_HAIL = 91


GROUP_LIGHTS = 1
GROUP_BLINDS = 2
GROUP_HEATING = 3
GROUP_COOLING = 9
GROUP_VENTILATION = 10
GROUP_WINDOW = 11
GROUP_RECICULATION = 12
GROUP_APARTMENT_VENTILATION = 64
GROUP_TEMPERATURE_CONTROL = 48
GROUP_AUDIO = 4
GROUP_VIDEO = 5
GROUP_JOKER = 8

SCENE_NAMES = {
    SCENE_PRESET0: "SCENE_PRESET0",
    SCENE_PRESET1: "SCENE_PRESET1",
    SCENE_PRESET2: "SCENE_PRESET2",
    SCENE_PRESET3: "SCENE_PRESET3",
    SCENE_PRESET4: "SCENE_PRESET4",
    SCENE_AUTO_STANDBY: "AUTO_STANDBY",
    SCENE_PANIC: "PANIC",
    SCENE_ENERGY_OVERLOAD: "ENERGY_OVERLOAD",
    SCENE_STANDBY: "STANDBY",
    SCENE_DEEP_OFF: "DEEP_OFF",
    SCENE_SLEEPING: "SLEEPING",
    SCENE_WAKEUP: "WAKEUP",
    SCENE_PRESENT: "PRESENT",
    SCENE_ABSENT: "ABSENT",
    SCENE_DOOR_BELL: "DOOR_BELL",
    SCENE_FIRE: "FIRE",
    SCENE_ALARM_1: "ALARM_SIGNAL_1",
    SCENE_ROOM_WAKEUP: "ROOM_WAKEUP",
    SCENE_ALARM_2: "ALARM_SIGNAL_2",
    SCENE_ALARM_3: "ALARM_SIGNAL_3",
    SCENE_ALARM_4: "ALARM_SIGNAL_4",
    SCENE_WIND: "WIND",
    SCENE_NO_WIND: "NO_WIND",
    SCENE_RAIN: "RAIN",
    SCENE_NO_RAIN: "NO_RAIN",
    SCENE_HAIL: "HAIL",
    SCENE_NO_HAIL: "NO_HAIL",
}
